language: c
sudo: false
dist: trusty

os:
  - windows
  - linux

compiler:
  - clang
  - gcc
  
script:
  - mkdir Release
  - cd Release
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build . # make
  - ctest .         # make test
