language: c
sudo: false
dist: trusty

os:
  - linux
  - osx
#  - windows

compiler:
  - clang
  - gcc
  
script:
  - mkdir Release
  - cd Release
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build .
  - ctest -C Release .
  - cpack .
