language: c
sudo: false
dist: trusty

compiler:
  - clang
  - gcc
  
script:
  - mkdir Release
  - cd Release
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build . # make
  - ctest .         # make test

#  - cd scripts/ && ./autogen.sh && cd ..
#  - ./configure
#  - make
#  - make check
#  - make dist
#  - cd test && ./duplicate.sh
