PROG=quidsum
CFLAGS=-Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security
LIBCUR=$(shell pwd)
LIBINC=$(shell dirname $(LIBCUR))/src
LINK=-lrt
INC=../include

.PHONY: clean all util util-debug run

all: util

util:
	gcc $(CFLAGS) -I$(INC) quidsum.c -L$(LIBINC) -lquid $(LINK) -o $(PROG)

util-debug:
	gcc -g $(CFLAGS) -I$(INC) -DDEBUG quidsum.c -L$(LIBINC) -lquid $(LINK) -o $(PROG)

run: all
	valgrind ./$(PROG)

clean:
	@rm -rf *.o .rnd $(PROG)
